name: "network"
version: "1.0"

channels:
  mychannel:
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
        discover: true
      peer1.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
        discover: true


organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
    certificateAuthorities:
      - ca.example.com
    adminPrivateKey:
      path: /home/pankaj/work/fabric-samples/first-network-original/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/ce293e7961c4f3dece4f2486f342c5253c53f054a17466cba4c1ed9ec6c2eb43_sk
    signedCert:
      path: /home/pankaj/work/fabric-samples/first-network-original/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem


orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: /home/pankaj/work/fabric-samples/first-network-original/crypto-config/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    eventUrl: grpcs://localhost:7053
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /home/pankaj/work/fabric-samples/first-network-original/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer1.org1.example.com:
    url: grpcs://localhost:8051
    eventUrl: grpcs://localhost:8053
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /home/pankaj/work/fabric-samples/first-network-original/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  certificateAuthorities:
    ca.org1.example.com:
      url: http://localhost:7054
      httpOptions:
        verify: false
      tlsCACerts:
        path: /home/pankaj/work/fabric-samples/first-network-original/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
      registrar:
        - enrollId: admin
          enrollSecret: adminpw
      caName: ca.example.com